[project]
name = ""
version = "0.0.1"
requires-python = "~=3.12.0"
dependencies = [
    "ansible",
    "passlib",
]

[dependency-groups]
dev = [
    "ansible-lint>=25.2.1",
    "ipykernel",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
