---
# tasks file for n8n

- name: Ensure n8n config directory exists
  ansible.builtin.file:
    path: "{{ n8n_config_folder }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  become: true

- name: Create temporary directory for Dockerfile
  ansible.builtin.tempfile:
    state: directory
    suffix: n8n_dockerfile
  register: dockerfile_temp_dir
  become: true

- name: Copy Dockerfile to remote host
  ansible.builtin.copy:
    src: Dockerfile
    dest: "{{ dockerfile_temp_dir.path }}/Dockerfile"
    mode: "0644"
  become: true

- name: Build custom n8n image with poppler-utils
  community.docker.docker_image:
    name: custom/n8n
    tag: latest
    source: build
    force_source: true
    build:
      path: "{{ dockerfile_temp_dir.path }}"
      pull: true
    state: present
  become: true

- name: Start n8n container
  community.docker.docker_container:
    name: n8n
    image: custom/n8n:latest
    pull: false
    image_name_mismatch: recreate
    restart_policy: unless-stopped
    user: "{{ uid }}:{{ uid }}"
    ports:
      - "{{ n8n_http_port }}:5678"
    volumes:
      - "{{ n8n_config_folder }}:/home/node/.n8n"
      - "{{ caddy_data_folder }}/caddy/pki/authorities/local:/opt/custom-certificates:ro"
      - n8n_tmp_data:/tmp/data
    env:
      GENERIC_TIMEZONE: "{{ system_timezone }}"
      TZ: "{{ system_timezone }}"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      WEBHOOK_URL: "https://{{ services['n8n'].domain }}"
      N8N_PROXY_HOPS: "1"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Allow self-signed certs for webhooks for now - fix later
      NODES_EXCLUDE: "[]"
      N8N_RESTRICT_FILE_ACCESS_TO: "/tmp/data"
    labels:
      homepage.group: "{{ services['n8n'].group }}"
      homepage.name: "{{ services['n8n'].name }}"
      homepage.href: "https://{{ services['n8n'].domain }}"
      homepage.icon: "{{ services['n8n'].icon }}"
      homepage.server: "{{ inventory_hostname }}"
      homepage.container: "n8n"
  become: true
