---
# Default variables for changedetection role
# Default port for the service
changedetection_http_port: "{{ ports.homelab_nuc.changedetection }}"

# Config folders
changedetection_config_folder: "{{ config_root }}/changedetection"