---
# defaults file for comfyui
comfyui_config_dir: /etc/comfyui # Static default config dir
comfyui_storage_path: /opt/comfyui/storage # Static default storage path
comfyui_image: yanwk/comfyui-boot:cu130-slim
comfyui_cli_args: "--fast"
comfyui_container_name: comfyui
